CREATE TABLE todo
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title     VARCHAR(255) not null,
    completed BOOLEAN not null ,
    user_id   BIGINT,
    CONSTRAINT pk_todo PRIMARY KEY (id)
);

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255) unique not null,
    password VARCHAR(255) not null ,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE todo
    ADD CONSTRAINT FK_TODO_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);